# Table of Contents

1. [SQLite Guide](#sqlite-guide)
   - [How to Install SQLite](#how-to-install-sqlite)
     - [Windows Installation](#windows-installation)
     - [Creating an SQLite Database](#creating-an-sqlite-database)
   - [Frequently Used Short-cut Command](#frequently-used-short-cut-command)
2. [SQLite Basics](#sqlite-basics)
   - [Tips](#tips)
   - [Creating a Table](#creating-a-table)
   - [Inserting Values](#inserting-values)
   - [Data Types](#data-types)
     - [Database-Specific Functions and Data Types](#database-specific-functions-and-data-types)
   - [Constraints](#constraints)
     - [Check Constraint](#check-constraint)
   - [Primary Keys](#primary-keys)
     - [Types of Primary Keys](#types-of-primary-keys)
   - [Deleting a Table](#deleting-a-table)

# SQLite Guide

## How to Install SQLite

### Windows Installation

1. Open PowerShell as an administrator.
2. Type the following command to install SQLite using Chocolatey:

```bash
choco install sqlite
```
3. To verify the installation, type:
```bash
sqlite3
```
### Creating an SQLite Database
1. Create a directory where you want to create your SQLite database.

2. Open PowerShell and navigate to that directory.

3. Create a new database with:

```bash
C:\Documents\yourDB> NewItem yourDB.db
```
Note: The file extension does not affect SQLite.
4. Use the ls command to check if the database file was created:

```bash
ls
```

### Frequently used short-cut command

* `Run` : `Ctrl + Enter`
  - To run a selected command or the entire cell
* `Run Current`: `Shift +Ctrl + Enter`
  - To run the command where the cursor is located.

## SQLite Basics

### Tips

* Comments:
  - Single line comment:`--` 
  - Multi-line comment:  `/* ~~~ */`
* End SQL statements with a semicolon `;`

### Creating a Table

In a relational database, tables store data. To create a table, you need to:

1. Define the name of the table.
2. Define the attributes (columns) in the table.

Example:
```sql
create table movies(
	title,
  released,
  overview,
  rating,
  director
);
```
* **Note**: This basic SQLite command does not specify data types. Other SQL databases require specific data types for each attribute.

### Inserting Values
1. Insert a single row:

```sql
INSERT INTO movies VALUES('The Godfather', 1980, 'The best movie in the world', 10, 'F.F.C');
```
  * Remember the order of the attributes.

2. Insert multiple rows:
```sql
INSERT INTO movies VALUES
('The Godfather', 1980, 'The best movie in the world', 10, 'F.F.C'),
('1984', 1983, 'super', 10, 'unknown');
```
  * Drawbacks: Must remember the order of attributes and provide values for all attributes. Use NULL for unknown values.
3. Insert specific attributes (recommended):
```sql
INSERT INTO movies (title) VALUES('The Lord of The Rings');

INSERT INTO movies (title, rating) VALUES('The Lord of The Rings II', 10);
```
  * This method allows other attributes to be NULL if not specified

### Data Types:
To ensure data integrity, specify data types for each attribute:
```sql
CREATE TABLE movies(
  title TEXT,
  released INTEGER,
  overview TEXT,
  rating REAL,
  director TEXT,
  for_kids INTEGER
) STRICT;
```
* Common Data Types:
  * `TEXT` for strings.
  * `INTEGER` for whole numbers.
  * `REAL` for floating-point numbers.
  * `BLOB` for binary data.
  * `SQLite does not support BOOLEAN`; use INTEGER with a range restriction instead.
  * `STRICt` for forcing the types.

#### Database-Specific Functions and Data Types
* **Important Note:** SQL functions and data types can vary between different database systems. `While the SQL syntax is standardized, specific implementations (like SQLite, MySQL, PostgreSQL, etc.) may use different function names or data type specifications.` It's crucial to consult the documentation for the specific SQL database you are using.
* For example, SQLite has a unique set of functions, such as LENGTH(X) for string length, and it supports only a limited set of data types compared to other databases.

### Constraints
Constraints are rules applied to data columns to ensure data integrity:
```sql
CREATE TABLE movies(
  title TEXT UNIQUE NOT NULL,
  released INTEGER NOT NULL,
  overview TEXT NOT NULL,
  rating REAL NOT NULL,
  director TEXT NOT NULL,
  for_kids INTEGER NOT NULL DEFAULT 0
) STRICT;
```
* **Common Constraints:**
  * UNIQUE: Ensures all values in a column are unique.
  * NOT NULL: Ensures a column cannot have NULL values.
  * DEFAULT: Sets a default value for a column if none is provided.
#### Check Constraint
`CHECK` constraints allow custom conditions to restrict data input:
  ```sql
  CREATE TABLE movies(
    title TEXT UNIQUE NOT NULL,
    released INTEGER NOT NULL CHECK (released > 0),
    overview TEXT NOT NULL CHECK (LENGTH(overview) <= 100),
    rating REAL NOT NULL CHECK (rating BETWEEN 0 AND 10),
    director TEXT NOT NULL,
    for_kids INTEGER DEFAULT 0 NOT NULL CHECK (for_kids = 0 OR for_kids = 1)
  ) STRICT;
  ```
* **Examples:**
  * CHECK (released > 0): Ensures released is a positive integer.
  * CHECK (LENGTH(overview) <= 100): Limits the length of overview to 100 characters.

### Primary Keys

Primary keys uniquely identify rows in a table and must be:

1. **Unique**
2. **Immutable**

#### Types of Primary Keys
1. **Natural Primary Key:** A key with a logical relationship to the data.
  ```sql
  CREATE TABLE movies(
    title TEXT PRIMARY KEY UNIQUE NOT NULL,
    released INTEGER NOT NULL CHECK (released > 0),
    overview TEXT NOT NULL CHECK (LENGTH(overview) <= 100),
    rating REAL NOT NULL CHECK (rating BETWEEN 0 AND 10),
    director TEXT NOT NULL,
    for_kids INTEGER DEFAULT 0 NOT NULL CHECK (for_kids = 0 OR for_kids = 1)
  ) STRICT;
  ```
2. **Surrogate Primary Key:** An artificial key with no relation to the data.
  ```sql
  CREATE TABLE movies(
    movie_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT UNIQUE NOT NULL,
    released INTEGER NOT NULL CHECK (released > 0),
    overview TEXT NOT NULL CHECK (LENGTH(overview) <= 100),
    rating REAL NOT NULL CHECK (rating BETWEEN 0 AND 10),
    director TEXT NOT NULL,
    for_kids INTEGER DEFAULT 0 NOT NULL CHECK (for_kids = 0 OR for_kids = 1)
  ) STRICT;
  ```
* `AUTOINCREMENT`: Ensures a unique identifier for each row, preventing reuse of IDs.

### Deleting a Table
To delete a table and its data:

```sql
drop table movies;
```
**Warning:** Dropping a table is irreversible; all data will be lost without warning.